"""Add plant details columns

Revision ID: cb62d8cfadac
Revises: db7f77975731
Create Date: 2025-10-17 14:56:56.347635

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cb62d8cfadac'
down_revision = 'db7f77975731'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plant_identification', 'user_id',
               existing_type=mysql.VARCHAR(length=36),
               comment='发起识别的用户 ID，用于关联用户',
               existing_nullable=False)
    op.alter_column('plant_identification', 'plant_id',
               existing_type=mysql.VARCHAR(length=36),
               comment='识别结果对应的植物 ID，如果找到匹配的植物则关联，否则为 NULL',
               existing_nullable=True)
    op.alter_column('plant_identification', 'scientific_name',
               existing_type=mysql.VARCHAR(length=255),
               comment="识别结果的植物学名，来自识别 API，如 'Rosa chinensis'",
               existing_nullable=False)
    op.alter_column('plant_identification', 'common_name',
               existing_type=mysql.VARCHAR(length=255),
               comment="识别结果的植物常用名，来自识别 API，如 '月季花'",
               existing_nullable=False)
    op.alter_column('plant_identification', 'confidence',
               existing_type=mysql.FLOAT(),
               comment='识别置信度，取值范围 0-1，1 表示 100% 确信，值越大识别准确度越高',
               existing_nullable=False)
    op.alter_column('plant_identification', 'image_url',
               existing_type=mysql.VARCHAR(length=500),
               comment='用户上传的识别图片 URL，保存在 S3 或本地服务器',
               existing_nullable=False)
    op.alter_column('plant_identification', 'suggestions',
               existing_type=mysql.JSON(),
               comment='\n        识别建议列表 JSON 数组，包含多个可能的识别结果：\n        [\n            {"scientific_name": "学名", "common_name": "常用名", "confidence": 0.92},\n            {"scientific_name": "学名", "common_name": "常用名", "confidence": 0.88},\n            ...\n        ]\n        ',
               existing_nullable=True)
    op.alter_column('plant_identification', 'latitude',
               existing_type=mysql.FLOAT(),
               comment='拍摄地点的纬度坐标，用于地理定位和地区性植物推荐',
               existing_nullable=True)
    op.alter_column('plant_identification', 'longitude',
               existing_type=mysql.FLOAT(),
               comment='拍摄地点的经度坐标，用于地理定位和地区性植物推荐',
               existing_nullable=True)
    op.alter_column('plant_identification', 'location_name',
               existing_type=mysql.VARCHAR(length=255),
               comment="拍摄地点的名称，如 '北京'、'公园' 等，用户可选填",
               existing_nullable=True)
    op.alter_column('plant_identification', 'user_feedback',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=50),
               comment="用户对识别结果的反馈，可能的值：'correct'（正确）、'incorrect'（错误）、'unknown'（不确定）",
               existing_nullable=True)
    op.alter_column('plant_identification', 'user_notes',
               existing_type=mysql.TEXT(),
               comment='用户对这个识别的附加说明或笔记',
               existing_nullable=True)
    op.alter_column('plant_identification', 'identification_source',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True,
               comment="识别的来源 API，如 'plants.id'、'other_api' 等，用于区分不同的识别服务")
    op.alter_column('plant_identification', 'request_id',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               comment='外部 API 返回的请求 ID，用于追踪和日志记录',
               existing_nullable=True)
    op.alter_column('plant_identification', 'processing_status',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=True,
               comment="处理状态，可能的值：'completed'（已完成）、'pending'（待处理）、'failed'（失败）")
    op.drop_column('plant_identification', 'error_message')
    op.drop_column('plant_identification', 'image_width')
    op.drop_column('plant_identification', 'raw_response')
    op.drop_column('plant_identification', 'image_height')
    op.alter_column('plants', 'scientific_name',
               existing_type=mysql.VARCHAR(length=255),
               comment="植物的学名（拉丁文），如 'Rosa chinensis'，全表唯一",
               existing_nullable=False)
    op.alter_column('plants', 'common_name',
               existing_type=mysql.VARCHAR(length=255),
               comment="植物的常用名称，如 '月季花'，用于用户查询",
               existing_nullable=False)
    op.alter_column('plants', 'family',
               existing_type=mysql.VARCHAR(length=255),
               comment="植物所属的科，如 '蔷薇科'",
               existing_nullable=True)
    op.alter_column('plants', 'genus',
               existing_type=mysql.VARCHAR(length=255),
               comment="植物所属的属，如 '蔷薇属'",
               existing_nullable=True)
    op.alter_column('plants', 'species',
               existing_type=mysql.VARCHAR(length=255),
               comment="植物的种名，如 '月季'",
               existing_nullable=True)
    op.alter_column('plants', 'description',
               existing_type=mysql.TEXT(),
               comment='植物的详细描述，100-200 字，包括外观、来源、用途等综合信息',
               existing_nullable=True)
    op.alter_column('plants', 'characteristics',
               existing_type=mysql.JSON(),
               comment="主要特征数组 JSON 格式，至少 5 个特征，如 ['特征1', '特征2', ...]",
               existing_nullable=True)
    op.alter_column('plants', 'care_info',
               existing_type=mysql.JSON(),
               comment='\n        养护指南 JSON 格式，包含 4 个养护项：\n        {\n            "sunlight": {"requirement": "光照需求", "description": "详细说明"},\n            "watering": {"requirement": "浇水频率", "description": "详细说明", "seasonal_variation": "季节变化"},\n            "soil": {"requirement": "土壤要求", "description": "详细说明", "ph_range": "pH范围"},\n            "temperature": {"requirement": "温度要求", "description": "详细说明", "cold_tolerance": "耐寒性"}\n        }\n        ',
               existing_nullable=True)
    op.alter_column('plants', 'plant_type',
               existing_type=mysql.VARCHAR(length=100),
               comment="植物类型，如 '草本植物'、'木本植物'、'灌木'、'多肉植物' 等",
               existing_nullable=True)
    op.alter_column('plants', 'habitat',
               existing_type=mysql.VARCHAR(length=255),
               comment="原生地环境描述，如 '温带温带地区'、'热带雨林' 等",
               existing_nullable=True)
    op.alter_column('plants', 'origin',
               existing_type=mysql.VARCHAR(length=255),
               comment="植物原产地，如 '中国'、'欧洲' 等",
               existing_nullable=True)
    op.alter_column('plants', 'propagation_method',
               existing_type=mysql.VARCHAR(length=255),
               comment="植物繁殖方式，如 '种子'、'扦插'、'分株'、'嫁接' 等，多种用逗号分隔",
               existing_nullable=True)
    op.alter_column('plants', 'common_pests',
               existing_type=mysql.JSON(),
               comment="常见病虫害 JSON 数组，如 ['蚜虫', '红蜘蛛', '白粉病', '黑斑病']",
               existing_nullable=True)
    op.alter_column('plants', 'height_range',
               existing_type=mysql.VARCHAR(length=100),
               comment="植物的典型高度范围，如 '30-50cm' 或 '1-2m'",
               existing_nullable=True)
    op.alter_column('plants', 'blooming_period',
               existing_type=mysql.VARCHAR(length=100),
               comment="植物的花期，如 '3-5月' 或 '四季开花' 或 '5-11月'",
               existing_nullable=True)
    op.alter_column('plants', 'toxicity',
               existing_type=mysql.TINYINT(display_width=1),
               comment='植物是否有毒，布尔值。True 表示有毒，False 表示无毒',
               existing_nullable=True)
    op.alter_column('plants', 'toxicity_description',
               existing_type=mysql.TEXT(),
               comment="毒性描述，说明有毒部位和毒性程度，如果无毒可为空或 '无毒'",
               existing_nullable=True)
    op.alter_column('plants', 'primary_image_url',
               existing_type=mysql.VARCHAR(length=500),
               comment='植物的主图 URL，在列表页和详情页展示的主要图片',
               existing_nullable=True)
    op.alter_column('plants', 'image_urls',
               existing_type=mysql.JSON(),
               comment="其他植物图片 URL 数组 JSON 格式，如 ['url1', 'url2', 'url3']",
               existing_nullable=True)
    op.alter_column('plants', 'seasonal_images',
               existing_type=mysql.JSON(),
               comment='\n        四季植物图片 JSON 格式，展示植物在不同季节的外观：\n        {\n            "spring": [{"url": "链接", "description": "春季描述"}],\n            "summer": [{"url": "链接", "description": "夏季描述"}],\n            "autumn": [{"url": "链接", "description": "秋季描述"}],\n            "winter": [{"url": "链接", "description": "冬季描述"}]\n        }\n        ',
               existing_nullable=True)
    op.alter_column('plants', 'is_verified',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否已验证。True 表示信息已审核确认，False 表示待审核',
               existing_nullable=True)
    op.alter_column('plants', 'is_featured',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否为特色推荐植物。True 表示推荐在首页展示，False 表示普通植物',
               existing_nullable=True)
    op.alter_column('plants', 'view_count',
               existing_type=mysql.INTEGER(),
               comment='植物详情页被查看的次数，用于统计热度',
               existing_nullable=True)
    op.alter_column('plants', 'identification_count',
               existing_type=mysql.INTEGER(),
               comment='植物被识别的次数，用于统计流行度和排序',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plants', 'identification_count',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='植物被识别的次数，用于统计流行度和排序',
               existing_nullable=True)
    op.alter_column('plants', 'view_count',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='植物详情页被查看的次数，用于统计热度',
               existing_nullable=True)
    op.alter_column('plants', 'is_featured',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='是否为特色推荐植物。True 表示推荐在首页展示，False 表示普通植物',
               existing_nullable=True)
    op.alter_column('plants', 'is_verified',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='是否已验证。True 表示信息已审核确认，False 表示待审核',
               existing_nullable=True)
    op.alter_column('plants', 'seasonal_images',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='\n        四季植物图片 JSON 格式，展示植物在不同季节的外观：\n        {\n            "spring": [{"url": "链接", "description": "春季描述"}],\n            "summer": [{"url": "链接", "description": "夏季描述"}],\n            "autumn": [{"url": "链接", "description": "秋季描述"}],\n            "winter": [{"url": "链接", "description": "冬季描述"}]\n        }\n        ',
               existing_nullable=True)
    op.alter_column('plants', 'image_urls',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment="其他植物图片 URL 数组 JSON 格式，如 ['url1', 'url2', 'url3']",
               existing_nullable=True)
    op.alter_column('plants', 'primary_image_url',
               existing_type=mysql.VARCHAR(length=500),
               comment=None,
               existing_comment='植物的主图 URL，在列表页和详情页展示的主要图片',
               existing_nullable=True)
    op.alter_column('plants', 'toxicity_description',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment="毒性描述，说明有毒部位和毒性程度，如果无毒可为空或 '无毒'",
               existing_nullable=True)
    op.alter_column('plants', 'toxicity',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='植物是否有毒，布尔值。True 表示有毒，False 表示无毒',
               existing_nullable=True)
    op.alter_column('plants', 'blooming_period',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment="植物的花期，如 '3-5月' 或 '四季开花' 或 '5-11月'",
               existing_nullable=True)
    op.alter_column('plants', 'height_range',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment="植物的典型高度范围，如 '30-50cm' 或 '1-2m'",
               existing_nullable=True)
    op.alter_column('plants', 'common_pests',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment="常见病虫害 JSON 数组，如 ['蚜虫', '红蜘蛛', '白粉病', '黑斑病']",
               existing_nullable=True)
    op.alter_column('plants', 'propagation_method',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment="植物繁殖方式，如 '种子'、'扦插'、'分株'、'嫁接' 等，多种用逗号分隔",
               existing_nullable=True)
    op.alter_column('plants', 'origin',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment="植物原产地，如 '中国'、'欧洲' 等",
               existing_nullable=True)
    op.alter_column('plants', 'habitat',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment="原生地环境描述，如 '温带温带地区'、'热带雨林' 等",
               existing_nullable=True)
    op.alter_column('plants', 'plant_type',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment="植物类型，如 '草本植物'、'木本植物'、'灌木'、'多肉植物' 等",
               existing_nullable=True)
    op.alter_column('plants', 'care_info',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='\n        养护指南 JSON 格式，包含 4 个养护项：\n        {\n            "sunlight": {"requirement": "光照需求", "description": "详细说明"},\n            "watering": {"requirement": "浇水频率", "description": "详细说明", "seasonal_variation": "季节变化"},\n            "soil": {"requirement": "土壤要求", "description": "详细说明", "ph_range": "pH范围"},\n            "temperature": {"requirement": "温度要求", "description": "详细说明", "cold_tolerance": "耐寒性"}\n        }\n        ',
               existing_nullable=True)
    op.alter_column('plants', 'characteristics',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment="主要特征数组 JSON 格式，至少 5 个特征，如 ['特征1', '特征2', ...]",
               existing_nullable=True)
    op.alter_column('plants', 'description',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='植物的详细描述，100-200 字，包括外观、来源、用途等综合信息',
               existing_nullable=True)
    op.alter_column('plants', 'species',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment="植物的种名，如 '月季'",
               existing_nullable=True)
    op.alter_column('plants', 'genus',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment="植物所属的属，如 '蔷薇属'",
               existing_nullable=True)
    op.alter_column('plants', 'family',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment="植物所属的科，如 '蔷薇科'",
               existing_nullable=True)
    op.alter_column('plants', 'common_name',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment="植物的常用名称，如 '月季花'，用于用户查询",
               existing_nullable=False)
    op.alter_column('plants', 'scientific_name',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment="植物的学名（拉丁文），如 'Rosa chinensis'，全表唯一",
               existing_nullable=False)
    op.add_column('plant_identification', sa.Column('image_height', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('plant_identification', sa.Column('raw_response', mysql.JSON(), nullable=True))
    op.add_column('plant_identification', sa.Column('image_width', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('plant_identification', sa.Column('error_message', mysql.TEXT(), nullable=True))
    op.alter_column('plant_identification', 'processing_status',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=20),
               nullable=False,
               comment=None,
               existing_comment="处理状态，可能的值：'completed'（已完成）、'pending'（待处理）、'failed'（失败）")
    op.alter_column('plant_identification', 'request_id',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='外部 API 返回的请求 ID，用于追踪和日志记录',
               existing_nullable=True)
    op.alter_column('plant_identification', 'identification_source',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False,
               comment=None,
               existing_comment="识别的来源 API，如 'plants.id'、'other_api' 等，用于区分不同的识别服务")
    op.alter_column('plant_identification', 'user_notes',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='用户对这个识别的附加说明或笔记',
               existing_nullable=True)
    op.alter_column('plant_identification', 'user_feedback',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment="用户对识别结果的反馈，可能的值：'correct'（正确）、'incorrect'（错误）、'unknown'（不确定）",
               existing_nullable=True)
    op.alter_column('plant_identification', 'location_name',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment="拍摄地点的名称，如 '北京'、'公园' 等，用户可选填",
               existing_nullable=True)
    op.alter_column('plant_identification', 'longitude',
               existing_type=mysql.FLOAT(),
               comment=None,
               existing_comment='拍摄地点的经度坐标，用于地理定位和地区性植物推荐',
               existing_nullable=True)
    op.alter_column('plant_identification', 'latitude',
               existing_type=mysql.FLOAT(),
               comment=None,
               existing_comment='拍摄地点的纬度坐标，用于地理定位和地区性植物推荐',
               existing_nullable=True)
    op.alter_column('plant_identification', 'suggestions',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='\n        识别建议列表 JSON 数组，包含多个可能的识别结果：\n        [\n            {"scientific_name": "学名", "common_name": "常用名", "confidence": 0.92},\n            {"scientific_name": "学名", "common_name": "常用名", "confidence": 0.88},\n            ...\n        ]\n        ',
               existing_nullable=True)
    op.alter_column('plant_identification', 'image_url',
               existing_type=mysql.VARCHAR(length=500),
               comment=None,
               existing_comment='用户上传的识别图片 URL，保存在 S3 或本地服务器',
               existing_nullable=False)
    op.alter_column('plant_identification', 'confidence',
               existing_type=mysql.FLOAT(),
               comment=None,
               existing_comment='识别置信度，取值范围 0-1，1 表示 100% 确信，值越大识别准确度越高',
               existing_nullable=False)
    op.alter_column('plant_identification', 'common_name',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment="识别结果的植物常用名，来自识别 API，如 '月季花'",
               existing_nullable=False)
    op.alter_column('plant_identification', 'scientific_name',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment="识别结果的植物学名，来自识别 API，如 'Rosa chinensis'",
               existing_nullable=False)
    op.alter_column('plant_identification', 'plant_id',
               existing_type=mysql.VARCHAR(length=36),
               comment=None,
               existing_comment='识别结果对应的植物 ID，如果找到匹配的植物则关联，否则为 NULL',
               existing_nullable=True)
    op.alter_column('plant_identification', 'user_id',
               existing_type=mysql.VARCHAR(length=36),
               comment=None,
               existing_comment='发起识别的用户 ID，用于关联用户',
               existing_nullable=False)
    # ### end Alembic commands ###
